import type { Metadata } from 'next'
import { Inter, Nunito } from 'next/font/google'
import '../globals.css'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

const nunito = Nunito({ subsets: ['latin'], variable: '--font-nunito' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ lng: string }>
}>) {
  const { lng } = await params
  return (
    <html lang={lng} className={clsx(inter.variable, nunito.variable)}>
      <body>{children}</body>
    </html>
  )
}
